apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-springboot-hello-docker-dn7c
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-springboot-hello-docker-dn7c
    app.kubernetes.io/part-of: ec-test
  name: java-springboot-hello-docker-dn7c
  namespace: zregvart-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: java-springboot-hello-docker-dn7c
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: java-springboot-hello-docker-dn7c
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:17fa352298f0bad63f922987df115fb9bfb3d7df0aa545bcd3e39bff49111a22
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
